'use strict';
// Optional same-origin backend. OPENAI_API_KEY is read only on the server.
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const MODEL = process.env.OPENAI_MODEL || 'gpt-4o-mini';
function send(res,status,body,type='application/json; charset=utf-8') { res.writeHead(status,{'content-type':type,'cache-control':'no-store'}); res.end(type.startsWith('application/json') ? JSON.stringify(body) : body); }
function staticFile(req,res) { const requested=req.url==='/'?'/kingmind-prototype.html':req.url.split('?')[0]; const safe=path.normalize(requested).replace(/^\.\.(\/|\\)/,''); const file=path.join(ROOT,safe); if(!file.startsWith(ROOT)||!fs.existsSync(file)||!fs.statSync(file).isFile()) return send(res,404,{error:'Not found'}); const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.wasm':'application/wasm','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'}; send(res,200,fs.readFileSync(file),types[path.extname(file)]||'application/octet-stream'); }
async function chat(req,res) { if(!process.env.OPENAI_API_KEY) return send(res,503,{error:'AI backend is not configured; using local responses.'}); let raw=''; for await(const chunk of req){raw+=chunk;if(raw.length>100000)return send(res,413,{error:'Request too large'});} let data; try{data=JSON.parse(raw);}catch{return send(res,400,{error:'Invalid JSON'});} const messages=Array.isArray(data.messages)?data.messages.slice(-20).map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'').slice(0,4000)})):[]; if(!messages.length)return send(res,400,{error:'messages is required'}); const response=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:'Sos KingMind, un entrenador de ajedrez amable. Respondé en español, con claridad y brevedad.'},...messages],temperature:.4,max_tokens:500})}); const result=await response.json(); if(!response.ok)return send(res,502,{error:'The AI provider returned an error.'}); return send(res,200,{reply:result.choices?.[0]?.message?.content||'No pude generar una respuesta.'}); }
http.createServer((req,res)=>{if(req.method==='POST'&&req.url==='/api/chat')return chat(req,res).catch(()=>send(res,502,{error:'AI request failed.'}));if(req.method==='GET')return staticFile(req,res);send(res,405,{error:'Method not allowed'});}).listen(PORT,()=>console.log(`KingMind listening on http://localhost:${PORT}`));
